language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to  setup db
services:
  - postgresql
before_script:
  - psql -c 'create database rmw;' -U postgres

deploy:
  provider: heroku
  api_key:
    secure: "637f46b6-d9d3-4c0d-a436-a7c552018a89"
  app: Ride-my-Way
  on:
    branch: api-v1-restructured
script: pytest

after_success: coveralls

